name: tts_service
description: "System to run TTS"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:

  dio: ^5.7.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  http: ^1.6.0
  just_audio: ^0.10.5

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1

